### ISSUE TITLE
How to display the main image after rendering?

### ISSUE THREAD

**Issue by wrong-age-98** [alberto-mate/CARLA-SB3-RL-Training-Environment#1]
I encountered a strange issue where the main image is not being displayed. I downloaded your code and ran the environment, but the main image is not showing. Have you encountered this issue before, and how can it be resolved?
![2023-07-14 22-50-47 的屏幕截图](https://github.com/alberto-mate/CARLA-SB3-RL-Training-Environment/assets/105617660/647ac752-7d42-41ec-8655-343db3468914)

**Comment by DeLeonOscar** [comment]
Hey how did you make it to work? I am getting this error **Carla ROOT has not been set**. 
My hardware is Carla 9.13 on Windows System.

**Comment by laolinde** [comment]
> I encountered a strange issue where the main image is not being displayed. I downloaded your code and ran the environment, but the main image is not showing. Have you encountered this issue before, and how can it be resolved? ![2023-07-14 22-50-47 的屏幕截图](https://private-user-images.githubusercontent.com/105617660/253605260-647ac752-7d42-41ec-8655-343db3468914.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MzA5OTMsIm5iZiI6MTcxMjYzMDY5MywicGF0aCI6Ii8xMDU2MTc2NjAvMjUzNjA1MjYwLTY0N2FjNzUyLTdkNDItNDFlYy04NjU1LTM0M2RiMzQ2ODkxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwMjQ0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTA3YWY2NWEzOWRjY2YwMmJmM2Q1MzE2ZmRiYTEwNWUxMTAyNjUwZTc3NTY2MjM1NjY3MDZhNGUxYTRlYzYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D_o57CmXK0f1ju-GDGPEV0n3R3otAYhmgN1tFjux5Us)

Hey, I met the same problem too.  Could you please advise me on how to address it?  I would greatly appreciate any suggestions or guidance you could provide.

**Comment by InitialZzz** [comment]
Hey, I met the same problem too. Could you please advise me on how to address it?

**Comment by iseecow** [comment]
Hi, I met this problem too. The training process seems still work, while I`m wondering how this could this be solved?

**Comment by iseecow** [comment]
I found that although the training code is not displayed, the test code can be displayed.

**Comment by alberto-mate** [comment]
Hi! To render the back-top camera view of the car during training, set the variable `activate_spectator=True.`

https://github.com/alberto-mate/CARLA-SB3-RL-Training-Environment/blob/73d158ff8fdfcc38025ddcd1cbd4f5439e1e53ba/train.py#L53C1-L54C1

Note that this flag is always set to `True` during testing/evaluation. However, in training, it’s `False` by default to save computational resources.

If you encounter any further issues, feel free to ask!
