### ISSUE TITLE
improvement

### ISSUE THREAD

**Issue by hzxBuaa** [alberto-mate/CARLA-SB3-RL-Training-Environment#4]
Hello, thank you very much for providing me with ideas through your work! Can I make improvements based on your work? How to cite?

**Comment by alberto-mate** [comment]
Hi, thank you for your comment! I'm glad you found my work helpful. You're welcome to build upon or make improvements to it. Just please make sure to cite the project properly. I’ve added a citation section in the README, which you can find it [here](https://github.com/alberto-mate/CARLA-SB3-RL-Training-Environment?tab=readme-ov-file#-citation).

**Comment by hzxBuaa** [comment]
ok, thank you very much!
