### ISSUE TITLE
Hello Alberto!

### ISSUE THREAD

**Issue by MasterYeChan** [alberto-mate/CARLA-SB3-RL-Training-Environment#5]
I have found your experiments to be very fascinating and have carefully reviewed and reproduced them myself.

I am currently working on my undergraduate thesis and would like to include your CARLA reinforcement learning performance comparisons in my paper, with proper citation and acknowledgment.

Would it be alright to use your work in this way? Thank you very much!

**Comment by alberto-mate** [comment]
Hi, thank you for your comment! I'm glad you found my work helpful. You're welcome to build upon or make improvements to it. Just please make sure to cite the project properly. I’ve added a citation section in the README, which you can find it [here](https://github.com/alberto-mate/CARLA-SB3-RL-Training-Environment?tab=readme-ov-file#-citation).

**Comment by MasterYeChan** [comment]
Thank you so much for your kind response! I’ll make sure to properly cite your project as described in the README. Your work has been incredibly helpful for my thesis!
